#!/usr/bin/env python
# -*- coding: utf-8 -*-
import logging
import argparse

from garuda import Garuda
from garuda.channels.rest import GAFalconChannel
from garuda.plugins.storage import GAMongoStoragePlugin
from garuda.plugins.authentication import GASimpleAuthenticationPlugin


def tdl_auth_function(request, session, root_object_class, storage_controller):
    """
    """
    auth = root_object_class()
    auth.api_key = session.uuid
    auth.password = None
    return auth

def start(falcon_port, sdk_name, mongo_host, mongo_port, mongo_db, redis_host, redis_port, redis_db):

    """
    """
    # redis
    redis_info = {'host': redis_host, 'port': redis_port, 'db': redis_db}

    #mongo
    mongo_uri = 'mongodb://%s:%d' % (mongo_host, mongo_port)

    # sdk info
    sdk_infos = [{'identifier': 'default', 'module': sdk_name}]

    channel = GAFalconChannel(port=falcon_port)
    storage_plugin = GAMongoStoragePlugin(db_name=mongo_db, mongo_uri=mongo_uri)
    authentication_plugin = GASimpleAuthenticationPlugin(auth_function=tdl_auth_function)

    garuda = Garuda(sdks_info=sdk_infos,
                    redis_info=redis_info,
                    channels=[channel],
                    plugins=[storage_plugin, authentication_plugin],
                    log_level=logging.DEBUG)
    garuda.start()


if __name__ == '__main__':

    parser = argparse.ArgumentParser(description="Bladerunner")

    parser.add_argument('--sdk-name',
                        dest='sdk_name',
                        help='the sdk module to use. Example "mysdk.v1_0"',
                        required=True,
                        type=str)

    parser.add_argument('--port',
                        dest='port',
                        help='the port of the falcon ReST channel.',
                        default=2000,
                        type=int)

    parser.add_argument('--mongo-host',
                        dest='mongo_host',
                        help='the hostname of the mongodb',
                        default='127.0.0.1',
                        type=str)

    parser.add_argument('--mongo-port',
                        dest='mongo_port',
                        help='the port name for mongodb',
                        default=27017,
                        type=int)

    parser.add_argument('--mongo-db',
                        dest='mongo_db',
                        help='the db name for mongodb',
                        default='garuda',
                        type=str)

    parser.add_argument('--redis-host',
                        dest='redis_host',
                        help='the hostname of the redis',
                        default='127.0.0.1',
                        type=str)

    parser.add_argument('--redis-port',
                        dest='redis_port',
                        help='the port name for redis',
                        default=6379,
                        type=int)

    parser.add_argument('--redis-db',
                        dest='redis_db',
                        help='the db number for redis',
                        default=0,
                        type=int)

    args = parser.parse_args()

    start(  falcon_port=args.port,
            sdk_name=args.sdk_name,
            mongo_host=args.mongo_host,
            mongo_port=args.mongo_port,
            mongo_db=args.mongo_db,
            redis_host=args.redis_host,
            redis_port=args.redis_port,
            redis_db=args.redis_db)


